version: '3'
services:
  profile:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/usr/src/app/
      - logvolume01:/var/log

volumes:
  logvolume01: {}
